# This is a basic workflow that is manually triggered

name: Build Static Doc Files

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

# on: push
on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    paths:
      - '**.md'
  pull_request:
    types: [opened, reopened]
    # Only trigger automatically when certain tags are added
    #tags:
    #- v1.**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-html:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
    # Runs a single command using the runners shell
    #- name: Send greeting
    #  run: echo "Hello ${{ github.event.inputs.name }}"
      
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: python -m pip install --upgrade pip setuptools wheel
    # Needed when using more than one repo
    # add 'monorepo' to mkdocs.yml file under plugins
    - run: pip install mkdocs-monorepo-plugin
    # Commenting out material insiders install until get proper token back.
    #- run: pip install git+https://${{ env.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: pip install mkdocs
    - run: pip install mkdocs-material
    - run: mkdocs build --site-dir ./site/$GITHUB_REF_NAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/19
        keep_files: true
