name: Build and Commit to PR Subdir

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
env:
  SITE_DIR: ${{ github.ref }}
  #SITE_DIR: subsite
# on: push
on:
  workflow_dispatch:
  #push:
    #branches:
    #  - 'dev'
    #paths:
    #  - '**.md'
  pull_request:
    types: [opened, reopened]
    # Only trigger automatically when certain tags are added
    #tags:
    #- v1.**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-html:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: Remove first part of PR ref
      uses: mad9000/actions-find-and-replace-string@3
      id: findandreplace1
      with:
        source: ${{ env.SITE_DIR }}
        find: 'refs/pull/'    
        replace: ''           

    - name: Remove last part of PR ref
      uses: mad9000/actions-find-and-replace-string@3
      id: findandreplace2
      with:
        source: ${{ steps.findandreplace1.outputs.value }}
        find: '/merge'    
        replace: '' 
        
    - name: Get the above output
      run: echo "The replaced value is ${{ steps.findandreplace2.outputs.value }}"
      
    - name: Checkout Dev
      uses: actions/checkout@v3
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: python -m pip install --upgrade pip setuptools wheel
    
    # Needed when using more than one repo
    # add 'monorepo' to mkdocs.yml file under plugins
    - run: pip install mkdocs-monorepo-plugin
    
    # Commenting out material insiders install until get proper token back.
    - run: pip install git+https://${{ env.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: pip install mkdocs
    #- run: pip install mkdocs-material
    
    - name: Build the Docs
      run: mkdocs build --no-directory-urls
      
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az login --service-principal -u e4c6c5fb-9968-4aac-bb7b-09adf7ae9ee7 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            echo "storage container create --name pr${{ steps.findandreplace2.outputs.value }} --public-access container --account-name quixdocs --auth-mode key"
            az storage container create --name pr${{ steps.findandreplace2.outputs.value }} --public-access container --account-name quixdocs --auth-mode key
            echo "az storage blob upload-batch --account-name quixdocs --auth-mode key -d 'pr${{ steps.findandreplace2.outputs.value }}' -s site"
            az storage blob upload-batch --account-name quixdocs --auth-mode key -d 'pr${{ steps.findandreplace2.outputs.value }}' -s site

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
          
    - name: Echo Site URL
      run: echo "Docs preview site available at https://quixdocs.blob.core.windows.net/pr${{ steps.findandreplace2.outputs.value }}/index.html"
      


